// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqhQ5FS33Ragv2oaMSlpXD5iKVACiB1_k',
    appId: '1:1036241225960:web:ca1a814e3c0258fb68615d',
    messagingSenderId: '1036241225960',
    projectId: 'tictok-kms6600',
    authDomain: 'tictok-kms6600.firebaseapp.com',
    storageBucket: 'tictok-kms6600.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAskTYwbt61ggg26fBGZnsow12ukKJLUkk',
    appId: '1:1036241225960:android:139b7371b85aad2368615d',
    messagingSenderId: '1036241225960',
    projectId: 'tictok-kms6600',
    storageBucket: 'tictok-kms6600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCli43tbVj9baqPfGRU28reiH_EGLYPwAk',
    appId: '1:1036241225960:ios:a5502606d2e1497c68615d',
    messagingSenderId: '1036241225960',
    projectId: 'tictok-kms6600',
    storageBucket: 'tictok-kms6600.appspot.com',
    androidClientId: '1036241225960-3khs1bh0vbu48v14ppjgjfo5l5h0am1l.apps.googleusercontent.com',
    iosClientId: '1036241225960-hekig7efb21r66cedqktrntf3gq402l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCli43tbVj9baqPfGRU28reiH_EGLYPwAk',
    appId: '1:1036241225960:ios:a5502606d2e1497c68615d',
    messagingSenderId: '1036241225960',
    projectId: 'tictok-kms6600',
    storageBucket: 'tictok-kms6600.appspot.com',
    androidClientId: '1036241225960-3khs1bh0vbu48v14ppjgjfo5l5h0am1l.apps.googleusercontent.com',
    iosClientId: '1036241225960-hekig7efb21r66cedqktrntf3gq402l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
